--
monitor:
  switcher:
    file:
      name: monitor

    status:
      online: 1
      offline: 2

      post:
        body: buffer-data

      result:
        add: 1
        delete: 2

--
cmdb:
  switcher:
    file:
      name: cmdb

      buffer:
        add: cmdb-add
        delete: cmdb-del

--
ping:
  switcher:
    file:
      buffer:
        add: ping-add
        delete: ping-del

--
log:
  name: compare.log
